name: Publish Package

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Source
        run: npm run build

      - name: Switch Registry
        uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@BlueSky-Digital-Labs"

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
